### ISSUE TITLE
Create fun visual / infographic that represents UX process checklist

### ISSUE THREAD

**Issue by s-duffey** [gctools-outilsgc/ux_research#15]
Once the UX team has completed our new process checklist, it would be fun to incorporate some visual design to create an infographic or poster that we can share and print within the team.

**Comment by MPM9000-zz** [comment]
Note: @LemieuxGen 

Met with @s-duffey & @amablex to determine a revised scope for this task. The concept has moved away from an info graphic that maps directly to the work done for UX Process.

An early requirement of the UX checklist was that the checklist could be used to piece together a solution. A series of info graphic cards could be created to facilitate the scoping of UX work required to piece together a particular solution

**Comment by LemieuxGen** [comment]
Moving back in inbox to have this assigned to someone else in the next sprint, based on priorities.

**Comment by amablex** [comment]
This is the presentation explaining the work done during the Sprint:

https://github.com/gctools-outilsgc/ux_prototypes/raw/master/UX_Checklist/UXDeckCards.pdf

**Comment by DonnaMonbourquette** [comment]
@PhilAndrecheck

**Comment by amablex** [comment]
@PhilAndrecheck you can review this as well
