### ISSUE TITLE
Create card sort test for OADW features

### ISSUE THREAD

**Issue by s-duffey** [gctools-outilsgc/ux_research#18]
Create a card sorting test in Optimal Workshop to help determine what OADW applications to develop and what features work well together. These results can be then compared to the OADW user stories to prioritize and choose apps to work on. 
In turn, validates what features would fit well in the Discussions app specifically.

**Comment by MGoodberry** [comment]
@beckyjeong First draft of cards and categories have been done in Optimal, please review for clarity, missing pieces and maybe some condensing. The test still requires pre and post-test questions. 

Here's a doc with an explanation of the test, and some notes for writing the questions: https://docs.google.com/document/d/19ZLqN7iagX_-I8R7IeYLk5lMqPhi9qVry5UJfOUYX9M/edit?usp=sharing

**Comment by s-duffey** [comment]
Will need to create pre and post questions. Putting back in progress.

**Comment by s-duffey** [comment]
Preview test: https://digienablementux.optimalworkshop.com/optimalsort/1oesb6x2

@LemieuxGen

**Comment by LemieuxGen** [comment]
@s-duffey @beckyjeong @DonnaMonbourquette Attached are my comments and changes. 
[Collaboartion features_user testing.docx](https://zube.io/files/tbs-sct/a40f56e37f4a566b1d68b1a3e9a0b138-collaboartion-features_user-testing.docx)
Most importantly, however, is that I had actually envision something different for this card sort. I was under the impression we were sorting the collaboration tools and services (the list of 20 from the user stories document) into groups, to help us understand the relationship between them. It would also help us know which services should be groups or have integration between them. Let's discuss.

**Comment by beckyjeong** [comment]
@LemieuxGen 

Changes made, all comments/questions in italics under each question.

Preview test: https://digienablementux.optimalworkshop.com/optimalsort/ay0d6120

**Comment by LemieuxGen** [comment]
Made additional changes based on new questionnaire and card sort. Please update card sort and share link once completed. [Collaboartion features_user testing_commentsGL.docx](https://zube.io/files/tbs-sct/720d93608488feeba2c114d509fdcb50-collaboartion-features_user-testing_commentsgl.docx)
