### ISSUE TITLE
Prepare for the promotion of the card sort of OADW features

### ISSUE THREAD

**Issue by s-duffey** [gctools-outilsgc/ux_research#20]
Once card sorting exercise is created, prepare communications to promote the card sort test.  

- [x] Contact POR coordinator to review restrictions. 
- [x] Write communications / ideas for promoting the test (to work with Comms team)
- [ ] Translation

**Comment by Troy-Lawson** [comment]
+comms

**Comment by LemieuxGen** [comment]
@s-duffey moving to backlog as it's unlikely that this will happen within this sprint.

**Comment by LemieuxGen** [comment]
@s-duffey @beckyjeong @DonnaMonbourquette Attached are my comments and changes. 
[Collaboartion features_user testing.docx](https://zube.io/files/tbs-sct/a40f56e37f4a566b1d68b1a3e9a0b138-collaboartion-features_user-testing.docx)
Most importantly, however, is that I had actually envision something different for this card sort. I was under the impression we were sorting the collaboration tools and services (the list of 20 from the user stories document) into groups, to help us understand the relationship between them. It would also help us know which services should be groups or have integration between them. Let's discuss.

**Comment by s-duffey** [comment]
For review @LemieuxGen : https://gcdocsp.tbssct.local/gcdocs/llisapi.dll?func=ll&objaction=overview&objid=34888295

**Comment by s-duffey** [comment]
Will need to add GCconnex groups to post in when my GCconnex starts working again.

**Comment by LemieuxGen** [comment]
@s-duffey Added a few comments and made a few changes to streamline. Would like to change the focus of the messaging, less about ED and grouping features, but more about understanding how people work and collaborate so that we can use this info to make important decisions and ensure they have access to the tools they need to do their work efficiently.

**Comment by s-duffey** [comment]
Thanks @LemieuxGen. I added "counter" comments to your comments, but otherwise accepted all the changes!

**Comment by s-duffey** [comment]
Let me know where this ends up after chatting with Pat and Krista.

**Comment by LemieuxGen** [comment]
Moving to "blocked" for now as we need to first get approval on proceeding with the user research. Goal will be to work with comms to figure out best way to promote this once we have the go-ahead.

**Comment by s-duffey** [comment]
@LemieuxGen to chat with Pat today, will be preparing messages before Tuesday, June 18

**Comment by LemieuxGen** [comment]
Content and comments were provided to Krista. With comms now. Study and comms to be released on Tuesday, June 18th. 
Moving this card to done.
