### ISSUE TITLE
Create proposal for OADW app card sort

### ISSUE THREAD

**Issue by s-duffey** [gctools-outilsgc/ux_research#24]
Create a proposal for the OADW app card sort to attain approval. Card sort is already created and available on Optimal Workshop. 

Proposal on GCDOSC: https://gcdocsp.tbssct.local/gcdocs/llisapi.dll?func=ll&objaction=overview&objid=34905872

Card sort preview: https://digienablementux.optimalworkshop.com/optimalsort/ay0d6120

**Comment by beckyjeong** [comment]
@s-duffey @LemieuxGen Card sorting questions for POR approval: [2019-05-23 collaboration-features_card_sorting_questions.docx](https://zube.io/files/tbs-sct/05c2b539352e7110e10b562d93fcb604-2019-05-23-collaboration-features_card_sorting_questions.docx)

**Comment by s-duffey** [comment]
For review @LemieuxGen https://docs.google.com/document/d/1TVm11RGZ3AzUZ9O1AhuIw_NAOx8gJ-yMxh1EPeCkUPY/edit#heading=h.pxvgtkmqwdca

**Comment by LemieuxGen** [comment]
Reviewed and finalized draft. Shared with Chris to get his input. Moving to done. Will create new card if further work is required.
